bsp.ref: add check for optee config
Without this patch, reason-ptxdist fails with

----------8<----------8<----------8<----------8<----------8<----------
rsc@leda:~/git/DistroKit$ reason-ptxdist
Exception during condition execution (kconfig.OPTEEConfig()['CFG_STM32MP13']):
Traceback (most recent call last):
  File "/home/rsc/git/reason/reason/measurements/file.py", line 33, in __init__
    out = session.target.get(filename.encode('utf-8'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsc/git/reason/reason/targets/ptxdist.py", line 111, in get
    raise TargetError("%s undefined" % alias)
reason.targets.TargetError: b'OPTEECONFIG' undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rsc/git/reason/reason/assertions.py", line 518, in check_condition
    result = eval_analyzer(condition, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsc/git/reason/reason/assertions.py", line 431, in eval_analyzer
    return eval(analyzer.replace('\n', ' '), context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/home/rsc/git/reason/reason/measurements/__init__.py", line 21, in __call__
    obj = super().__call__(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rsc/git/reason/reason/measurements/kconfig.py", line 141, in __init__
    super().__init__(filename)
  File "/home/rsc/git/reason/reason/measurements/kconfig.py", line 16, in __init__
    super().__init__(filename)
  File "/home/rsc/git/reason/reason/measurements/file.py", line 37, in __init__
    raise UnavailableError from e
reason.measurements.UnavailableError
----------8<----------8<----------8<----------8<----------8<----------

Fixes fb553e6654dd32068ddc1224d1d325f7a3b0d80a.

Suggested-by: Michael Olbrich <m.olbrich@pengutronix.de>
Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>