blspec-entry: Backport fix from ptxdist master
Backport PTXdist commit 0d360df876bc26f709cf (2024-02-02, Alexander
Dahl: "blspec-entry: Fix kernel entry for FIT image"), otherwise
barebox fails when trying to boot a FIT image like this:

    ERROR: could not open /mnt/mmc0.1//boot//boot/linux.fit: No such file or directory
    ERROR: blspec: Booting failed

Signed-off-by: Alexander Dahl <ada@thorsis.com>
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.pengutronix.de/20240306092530.1448784-3-a.fatoum@pengutronix.de
Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>